#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Padavan CI B70

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
env:
  BUILD_OWNER: lee29	
  TNAME: B70
  T_NAMES: "B70"
  BASE_PATH: padavan                # 基础目录
  PUBLIC_PATH: public               # 公共目录
  PUBLIC_SH: public.sh              # 公共命令
  THEME_PATH: theme
  CLONE_URL: https://github.com/chongshengB/rt-n56u.git    # padavan  地址
  CLONE_BRANCH: master              # padavan 分支
  WORK_PATH: /opt/rt-n56u           # 工作目录 一定要加 /
  RECOVERY_SSPBINREMOTEDOWNLOAD: true   #是否替换ssp版本
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 $CLONE_URL -b $CLONE_BRANCH $WORK_PATH
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        
        # mkdir -p toolchain-3.4.x
        # wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
        # tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
        mkdir -p /opt/images/
    - name: 替换配置和主题
      run: |
        # 循环替换自定义默认模板和构建，单个设备的 sh 拷贝 t_item 需要编译的固件名字
        for t_item in $T_NAMES;
        do
        if [ -f $BASE_PATH/$t_item/${t_item}.config ] ; then
          mv -f $BASE_PATH/$t_item/${t_item}.config $WORK_PATH/trunk/configs/templates/${t_item}.config
          echo "${t_item} config文件拷贝成功"
        fi
        if [ -f $BASE_PATH/$t_item/replace/shadowsocks.sh ] ; then
          mv -f $BASE_PATH/$t_item/replace/shadowsocks.sh $WORK_PATH/trunk/user/shadowsocks/scripts/shadowsocks.sh
        echo "shadowsocks SH文件拷贝成功"
        fi
        if [ -f $BASE_PATH/$t_item/replace/defaults.h ] ; then
          mv -f $BASE_PATH/$t_item/replace/defaults.h $WORK_PATH/trunk/user/shared/defaults.h
          echo "${t_item} 配置文件拷贝成功"
        fi
        if [ ! -d $BASE_PATH/$t_item/$THEME_PATH ] ; then
          echo "${BASE_PATH}/${t_item}/${THEME_PATH} 自定义主题文件夹未找到"
        elif [! -d $WORK_PATH/$THEME_PATH ] ; then
              cp -r $BASE_PATH/$t_item/$THEME_PATH  $WORK_PATH/
              echo "${THEME_PATH} 自定义主题文件夹拷贝成功"  
           else
              rm -rf $WORK_PATH/$THEME_PATH
              cp -r $BASE_PATH/$t_item/$THEME_PATH  $WORK_PATH/
              sudo rm -rf $WORK_PATH/trunk/user/www/n56u_ribbon_fixed/bootstrap
              sudo rm -rf $WORK_PATH/trunk/user/www/n56u_ribbon_fixed/images
              cp -rf $WORK_PATH/$THEME_PATH/. $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
              echo "${THEME_PATH} 复制主题文件结束"  
        fi
        done
    - name: 加载机型配置
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config

    - name: 替换ssp
      if: env.RECOVERY_SSPBINREMOTEDOWNLOAD == 'true'
      run: |
        cp -f $BASE_PATH/$TNAME/replace/ssp/shadowsocks.sh $WORK_PATH/trunk/user/shadowsocks/scripts
        cp -f $BASE_PATH/$TNAME/replace/ssp/defaults.c $WORK_PATH/trunk/user/shared
        cp -f $BASE_PATH/$TNAME/replace/ssp/variables.c $WORK_PATH//trunk/user/httpd
        cp -f $BASE_PATH/$TNAME/replace/ssp/Shadowsocks.asp $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
        cd $WORK_PATH/trunk/user/shared
        sed -i "s#https://cdn.jsdelivr.net/gh/Padavan_CI/ssp/trojan#https://cdn.jsdelivr.net/gh/${BUILD_OWNER}/AutoBuild-Padavan/${BASE_PATH}/B70/replace/ssp/trojan#g" ./defaults.c
        sed -i "s#https://cdn.jsdelivr.net/gh/Padavan_CI/ssp/v2ray#https://cdn.jsdelivr.net/gh/${BUILD_OWNER}/AutoBuild-Padavan/${BASE_PATH}/B70/replace/ssp/v2ray#g" ./defaults.c
        #cd $WORK_PATH/trunk/user/unblockmusic/scripts
        #sed -i "s#https://cdn.jsdelivr.net/gh/chongshengB/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusic#https://cdn.jsdelivr.net/gh/${BUILD_OWNER}/AutoBuild-Padavan/${BASE_PATH}/B70/replace/unblockmusic/UnblockNeteaseMusic#g" ./unblockmusic.sh
        
    - name: 替换frp_script_sh              #替换frp脚本
      run: |        
        cp -f $BASE_PATH/$TNAME/replace/frp_script.sh $WORK_PATH/trunk/user/frp
        cd $WORK_PATH/trunk/user/frp
        echo "更改frpc版本"
        sed -i "s/0.29.0/0.34.1/g" ./Makefile
        echo "替换默认frpc脚本配置"
        sudo chmod +x ./frp_script.sh
        
    - name: 加载diy配置              #自定义diy配置
      run: |        
        cp -f $BASE_PATH/$TNAME/B70.sh  $WORK_PATH/trunk
        cd $WORK_PATH/trunk
        sudo chmod +x ./B70.sh
        echo "执行B70_SH"
        sudo $WORK_PATH/trunk/B70.sh 
        
    - name: 清理树并开始编译
      run: |               
        cd /opt/rt-n56u/trunk   
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
        
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages-B70
        path: /opt/images
    
    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && success()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${IMAGES_PATH} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        
    - name: Upload firmware to WeTransfer
      if: env.UPLOAD_WETRANSFER == 'true' && success()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${IMAGES_PATH} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
